export const REVIEW_TAG_OPTIONS = [
    'Tough Grader',
    'Get Ready To Read',
    'Participation Matters',
    'Extra Credit',
    'Group Projects',
    'Amazing Lectures',
    'Clear Grading Criteria',
    'Gives Good Feedback',
    'Inspirational',
    'Lots Of Homework',
    'Hilarious',
    'Beware Of Pop Quizzes',
    'So Many Papers',
    'Caring',
    'Respected',
    'Lecture Heavy',
    'Test Heavy',
    'Graded By Few Things',
    'Accessible Outside Class',
    'Online Savvy',
] as const;

export type ReviewTagOption = (typeof REVIEW_TAG_OPTIONS)[number];

export const GRADE_OPTIONS = [
    'A',
    'A-',
    'B+',
    'B',
    'B-',
    'C+',
    'C',
    'C-',
    'D+',
    'D',
    'D-',
    'F',
    'Pass',
    'No Pass',
    'Withdrawn',
    'Incomplete',
    'Other',
];
